spring.application.name=ChatApplication
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/chatdb
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.h2.console.enabled=true

spring.data.redis.host=redis-15811.crce185.ap-seast-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=15811
spring.data.redis.password=gtYNYNAysJewKtc96v9xJ3wHsYRQfbwr
spring.data.redis.timeout=2000ms
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#spring.jackson.serialization.wr=false

chat.websocket.endpoint=/ws
chat.websocket.app-destination-prefix=/app
chat.websocket.topic-prefix=/topic
chat.websocket.user-prefix=/user

logging.level.org.example.chatapplication.Service.AuthService=DEBUG

