package org.example.chatapplication.Model.Enum;

public enum AdminAuditAction {
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_LOCKED,
    USER_UNLOCKED,
    USER_ROLE_CHANGED,
    USER_SESSIONS_REVOKED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    MESSAGE_DELETED_BY_ADMIN,
    FILE_DELETED_BY_ADMIN,
    BROADCAST_CREATED,
    BROADCAST_DELETED,
    IMPERSONATION_CREATED,
    IMPERSONATION_REVOKED,
    AI_POLICY_UPDATED
}

